---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp:
  labels:
    app: catsndogs
  name: catsndogs-deploy
  namespace: cnd
  annotations:
  # Container Image Automated Updates
    flux.weave.works/automated: "true"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: catsndogs
  template:
    metadata:
      labels:
        app: catsndogs
    spec:
      containers:
      - image: 216888949630.dkr.ecr.us-east-1.amazonaws.com/catsndogs:93b532d1
        name: catsndogs
